"""empty message

Revision ID: 6960296ad4af
Revises: eb4512384c05
Create Date: 2018-07-31 11:49:40.359190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6960296ad4af'
down_revision = 'eb4512384c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin_approved')
    # ### end Alembic commands ###
