"""users table

Revision ID: d91be91c6895
Revises: 
Create Date: 2018-06-26 13:21:37.860473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91be91c6895'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('firstName', sa.String(length=16), nullable=True),
    sa.Column('lastName', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('photo_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
