"""users table

Revision ID: eb4512384c05
Revises: d91be91c6895
Create Date: 2018-07-23 10:00:50.781835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4512384c05'
down_revision = 'd91be91c6895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
